---
- name: Configure Vector | ensure what directory exists
  file:
    path: "{{ vector_config_dir }}"
    state: directory
    mode: 0755
- name: Configure Vector | Template config
  ansible.builtin.template:
    src: vector.yml.j2
    mode: 0644
    dest: "{{ vector_config_dir }}/vector.yml"
  notify: restart vector service
